//
// Created by RUPC on 2023/11/30.
//

#ifndef UV_K5_FIRMWARE_CUSTOM_0_17_CHINESE_H
#define UV_K5_FIRMWARE_CUSTOM_0_17_CHINESE_H
#include "font.h"
// ASCII label, valid in every language build
#define STR_CW_TONE "CWTone"
#if ENABLE_CHINESE_FULL!=4 || defined(ENABLE_ENGLISH)
#ifdef ENABLE_ENGLISH
#define STR_STEP_FREQ "Step"
#define STR_RX_DCS "RxDCS"
#define STR_RX_CTCSS "RxCTCS"
#define STR_TX_DCS "TxDCS"
#define STR_TX_CTCSS "TxCTCS"
#define STR_TX_OFFSET_DIR "TxODir"
#define STR_TX_OFFSET_FREQ "TxOffs"
#define STR_BUSY_CHANNEL_LOCKOUT "BusyCL"
#define STR_COMPANDER "Compnd"
#define STR_SAVE_CHANNEL "ChSave"
#define STR_DELETE_CHANNEL "ChDele"
#define STR_NAME_CHANNEL "ChName"
#define STR_CHANNEL_SCAN_LIST "SList"
#define STR_SCAN_LIST1 "SList1"
#define STR_SCAN_LIST2 "SList2"
#define STR_SCAN_RESUME_MODE "ScnRev"
#define STR_TX_TIMEOUT "TxTOut"
#define STR_POWER_SAVE_MODE "BatSav"
#define STR_MIC_GAIN "Mic"
#define STR_CHANNEL_DISPLAY_MODE "ChDisp"
#define STR_AUTO_BACKLIGHT "BackLt"
#define STR_BACKLIGHT_BRIGHTNESS "Light"
#define STR_ROGER_BEEP "Roger"
#define STR_TAIL_TONE_ELIM "STE"
#define STR_REPEATER_TAIL_TONE_ELIM "RP STE"
#define STR_ONE_KEY_CALL "1 Call"
#define DTMF_ID "D ID"
#define STR_DTMF_UP_CODE "UPCode"
#define STR_DTMF_DOWN_CODE "DWCode"
#define STR_DTMF_PTT_ID "PTT ID"
#define STR_DTMF_SIDETONE "D ST"
#define STR_DTMF_RESPONSE "D Resp"
#define STR_DTMF_HOLD "D Hold"
#define STR_DTMF_PRELOAD "D Prel"
#define STR_DTMF_CONTACTS "D List"
#define STR_DTMF_LIVE_DISPLAY "D Live"
#define STR_AM_AUTO_GAIN "AM Fix"
#define STR_RX_TX_MODE "RxMode"
#define STR_SQUELCH_LEVEL "Sql"
#define STR_BAND_UNLOCK "F Lock"
#define STR_TX_200M "Tx 200"
#define STR_TX_350M "Tx 350"
#define STR_TX_500M "Tx 500"
#define STR_RX_350M "350 En"
#define STR_BATTERY_CALIBRATION "BatCal"
#define STR_BATTERY_CAPACITY "BatVol"
#define STR_SETTINGS_RESET "Reset"
#define STR_TX_EQ_RX "OFF"
#define STR_TX_EQ_RX_PLUS_OFFSET "+"
#define STR_TX_EQ_RX_MINUS_OFFSET "-"
#define STR_OFF "OFF"
#define STR_ON "ON"
#define STR_LEVEL_ONE "1:1"
#define STR_LEVEL_TWO "1:2"
#define STR_LEVEL_THREE "1:3"
#define STR_LEVEL_FOUR "1:4"
#define STR_THIRTY_SECONDS "30 sec"
#define STR_ONE_MINUTE "1 min"
#define STR_TWO_MINUTES "2 min"
#define STR_THREE_MINUTES "3 min"
#define STR_FOUR_MINUTES "4 min"
#define STR_FIVE_MINUTES "5 min"
#define STR_SIX_MINUTES "6 min"
#define STR_SEVEN_MINUTES "7 min"
#define STR_EIGHT_MINUTES "8 min"
#define STR_NINE_MINUTES "9 min"
#define STR_FIFTEEN_MINUTES "15 min"
#define STR_MAIN_CH_RX_TX "MAIN\nONLY"
#define STR_DUAL_CH_RX "DUAL RX\nRESPOND"
#define STR_MAIN_TX_SUB_RX "CROSS\nBAND"
#define STR_MAIN_TX_DUAL_RX "MAIN TX\nDUAL RX"
#define STR_RESUME_5S_AFTER_SIGNAL "TIME"
#define STR_RESUME_WHEN_CARRIER_STOPS "CARRIER"
#define STR_STOP_ON_SIGNAL "STOP"
#define STR_FREQUENCY "FREQ"
#define STR_CHANNEL_NUMBER "CHANNEL\nNUMBER"
#define STR_NAME "NAME"
#define STR_NAME_PLUS_FREQ "NAME +\nFREQ"
#define STR_NO_RESPONSE "DO\nNOTHING"
#define STR_LOCAL_RING "RING"
#define STR_REPLY_RESPONSE "REPLY"
#define STR_LOCAL_RING_AND_REPLY "BOTH"
#define STR_NO_SEND "OFF"
#define STR_UP_CODE "UP CODE"
#define STR_DOWN_CODE "DOWN CODE"
#define STR_UP_PLUS_DOWN_CODE "UP+DOWN\nCODE"
#define STR_QUINDAR_CODE "APOLLO\nQUINDAR"
#define STR_OFF "OFF"
#define STR_ROGER_END_TONE "ROGER"
#define STR_VFO_SETTINGS "VFO"
#define STR_ALL_SETTINGS "ALL"
#define STR_DISABLE_ALL "DISABLE\nALL"
#define STR_UNLOCK_ALL "UNLOCK\nALL"
#define STR_FIVE_SECONDS "5 sec"
#define STR_TEN_SECONDS "10 sec"
#define STR_TWENTY_SECONDS "20 sec"
#define STR_ON_TX "TX"
#define STR_ON_RX "RX"
#define STR_ON_TX_AND_RX "TX/RX"
#define STR_ALL "ALL"
#define STR_SCAN "Scan"
#define STR_LOW_VOLTAGE "LOW VOL"
#define STR_BUSY "BUSY"
#define STR_TX_DISABLED "DISABLE"
#define STR_TX_TIMEOUT "TxTOut"
#define STR_HIGH_VOLTAGE "HIGH VOL"
#define STR_PRESS_EXIT_KEY "Press EXIT"
#define STR_SAVE_PROMPT "SAVE?"
#define STR_SAVED "SAVED!"
#define STR_DELETE_PROMPT "DEL?"
#define STR_LIST "List"
#define STR_CTCSS "CTCS"
#define STR_DCS "DCS"
#define STR_PICTURE "PIC"
#define STR_TEXT_MESSAGE "TxT"
#define STR_SIDE_KEY1_SHORT_PRESS "F1Shrt"
#define STR_SIDE_KEY1_LONG_PRESS "F1Long"
#define STR_SIDE_KEY2_SHORT_PRESS "F2Shrt"
#define STR_SIDE_KEY2_LONG_PRESS "F2Long"
#define STR_M_KEY_LONG_PRESS "M Long"
#define STR_FLASHLIGHT "LIGHT"
#define STR_SWITCH_TX_POWER "POWER"
#define STR_MONITOR "MONITOR"
#define STR_VOX_TX "VOX"
#define STR_FM_RADIO "FM RADIO"
#define STR_LOCK_KEYPAD "LOCK KEY"
#define STR_SWITCH_VFO "SWITCH VFO"
#define STR_SWITCH_VFO_MR_MODE "VFO/MR"
#define STR_SWITCH_MODULATION "Demodu"
#define STR_DTMF_DECODE "D Decd"
#define STR_SWITCH_BANDWIDTH "W/N"
#define STR_SQL_ADJUST "SQL ADJ"
#define STR_BANDWIDTH "W/N"
#define STR_WIDE_BAND "WIDE"
#define STR_NARROW_BAND "NARROW"
#define STR_MAIN_CH_TX "MAIN SEND"
#define STR_SUB_CH_TX "DUAL SEND"
#define STR_POWER_ON_DISPLAY "POnMsg"


#else
#define STR_STEP_FREQ  "\x01\x02\x03\x04"
#define STR_RX_DCS  "\x05\x06\x07\x08\x09\x0B"
#define STR_RX_CTCSS  "\x05\x06\x0C\x0D\x09\x0B"
#define STR_TX_DCS  "\x0E\x0F\x07\x08\x09\x0B"
#define STR_TX_CTCSS  "\x0E\x0F\x0C\x0D\x09\x0B"
#define STR_TX_OFFSET_DIR  "\x03\x10\x11\x12"
#define STR_TX_OFFSET_FREQ  "\x03\x10\x03\x04"
#define STR_BUSY_CHANNEL_LOCKOUT  "\x15\x16\x17\x0E"
#define STR_COMPANDER  "\x18\x19"
#define STR_SAVE_CHANNEL  "\x1A\x1B\x1C\x1D"
#define STR_DELETE_CHANNEL  "\x1E\x1F\x1C\x1D"
#define STR_NAME_CHANNEL  "\x7F\x80\x1C\x1D"
#define STR_CHANNEL_SCAN_LIST  "\x1C\x1D\x81\x82\x83\x84"
#define STR_SCAN_LIST1  "\x81\x82\x83\x84\x31"
#define STR_SCAN_LIST2  "\x81\x82\x83\x84\x32"
#define STR_SCAN_RESUME_MODE  "\x85\x86\x87\x88\x0C\x89"
#define STR_TX_TIMEOUT  "\x0E\x0F\x8A\x8B"
#define STR_POWER_SAVE_MODE  "\x8C\x8D\x0C\x89"
#define STR_MIC_GAIN  "\x8E\x8F\x90\x91\x92"
#define STR_CHANNEL_DISPLAY_MODE  "\x1C\x1D\x93\x94\x0C\x89"
#define STR_AUTO_BACKLIGHT  "\x95\x96\x97\x98"
#define STR_BACKLIGHT_BRIGHTNESS  "\x97\x98\x99\x9A"
#define STR_ROGER_BEEP  "\x9B\x9C\x0B"
#define STR_TAIL_TONE_ELIM  "\x9C\x0B\x9D\x1F"
#define STR_REPEATER_TAIL_TONE_ELIM  "\x9E\x9F\xA0\x9C\x0B\x9D\x1F"
#define STR_ONE_KEY_CALL  "\xA1\xA2\xA3\xA4"
#define DTMF_ID  "\x44\x54\x4D\x46\x20\x49\x44"
#define STR_DTMF_UP_CODE  "\x44\x54\x4D\x46\xA5\xA6\xA7"
#define STR_DTMF_DOWN_CODE  "\x44\x54\x4D\x46\xA8\xA6\xA7"
#define STR_DTMF_PTT_ID  "\x44\x54\x4D\x46\x0E\x0F"
#define STR_DTMF_SIDETONE  "\x44\x54\x4D\x46\xA9\x0B"
#define STR_DTMF_RESPONSE  "\x44\x54\x4D\x46\xAA\xAB"
#define STR_DTMF_HOLD  "\x44\x54\x4D\x46\x88\xAC"
#define STR_DTMF_PRELOAD  "\x44\x54\x4D\x46\xAD\xAE\xAF"
#define STR_DTMF_CONTACTS  "\x44\x54\x4D\x46\xB0\xB1\xB2"
#define STR_DTMF_LIVE_DISPLAY  "\x44\x54\x4D\x46\x93\x94"
#define STR_AM_AUTO_GAIN  "\x41\x4D\x95\x96\x91\x92"
#define STR_RX_TX_MODE  "\x06\x0E\x0C\x89"
#define STR_SQUELCH_LEVEL  "\xB3\xB4\xB5\xB6"
#define STR_BAND_UNLOCK  "\x03\xB7\xB8\xB9"
#define STR_BATTERY_CALIBRATION  "\x8D\xBA\xBB\x18"
#define STR_BATTERY_CAPACITY  "\x8D\xBA\xBC\xBD"
#define STR_SETTINGS_RESET  "\xBE\x07\x88\xAC"
#define STR_TX_EQ_RX  "\x0E\x0F\x3D\x05\x06"
#define STR_TX_EQ_RX_PLUS_OFFSET  "\x0E\x0F\x3D\n\x05\x06\x2B\xBF\xC0"
#define STR_TX_EQ_RX_MINUS_OFFSET  "\x0E\x0F\x3D\n\x05\x06\x2D\xBF\xC0"
#define STR_OFF  "\xC1\xC2"
#define STR_ON  "\xC3\xC4"
#define STR_LEVEL_ONE  "\x31\x20\xB6"
#define STR_LEVEL_TWO  "\x32\x20\xB6"
#define STR_LEVEL_THREE  "\x33\x20\xB6"
#define STR_LEVEL_FOUR  "\x34\x20\xB6"
#define STR_THIRTY_SECONDS  "\x33\x30\x20\xC5"
#define STR_ONE_MINUTE  "\x31\x20\xC6"
#define STR_TWO_MINUTES  "\x32\x20\xC6"
#define STR_THREE_MINUTES  "\x33\x20\xC6"
#define STR_FOUR_MINUTES  "\x34\x20\xC6"
#define STR_FIVE_MINUTES  "\x35\x20\xC6"
#define STR_SIX_MINUTES  "\x36\x20\xC6"
#define STR_SEVEN_MINUTES  "\x37\x20\xC6"
#define STR_EIGHT_MINUTES  "\x38\x20\xC6"
#define STR_NINE_MINUTES  "\x39\x20\xC6"
#define STR_FIFTEEN_MINUTES  "\x31\x35\x20\xC6"
#define STR_MAIN_CH_RX_TX  "\xC7\x1C\x1D\n\x05\x06\x0E\xC8"
#define STR_DUAL_CH_RX  "\xC9\x1C\x1D\n\x05\x06"
#define STR_MAIN_TX_SUB_RX  "\xC7\x1C\x1D\x0E\xC8\n\xCA\x1C\x1D\x05\x06"
#define STR_MAIN_TX_DUAL_RX  "\xC7\x1C\x1D\x0E\xC8\n\xC9\x1C\x1D\x05\x06"
#define STR_RESUME_5S_AFTER_SIGNAL  "\x15\x1C\xCB\n\x35\xC5\xCC\x85\x86"
#define STR_RESUME_WHEN_CARRIER_STOPS  "\x1C\xCB\xCD\xCE\xCC\n\x85\x86"
#define STR_STOP_ON_SIGNAL  "\x15\x1C\xCB\xCC\n\xCD\xCE\x85\x86"
#define STR_FREQUENCY  "\x03\x04"
#define STR_CHANNEL_NUMBER  "\x1C\x1D\xCB"
#define STR_NAME  "\x80\xCF"
#define STR_NAME_PLUS_FREQ  "\x80\xCF\x2B\n\x03\x04"
#define STR_NO_RESPONSE  "\xD0\xAA\xAB"
#define STR_LOCAL_RING  "\xD1\xD2\xAA\xD3"
#define STR_REPLY_RESPONSE  "\xD4\x88\xAA\xAB"
#define STR_LOCAL_RING_AND_REPLY  "\xD1\xD2\xAA\xD3\n\xD4\x88\xAA\xAB"
#define STR_NO_SEND  "\xD0\x0E\x0F"
#define STR_UP_CODE  "\xA5\xA6\xA7"
#define STR_DOWN_CODE  "\xA8\xA6\xA7"
#define STR_UP_PLUS_DOWN_CODE  "\xA5\xA6\x2B\xA8\xA6\xA7"
#define STR_QUINDAR_CODE  "\x51\x75\x69\x6E\x64\x61\x72\xA7"
#define STR_OFF  "\xC1\xC2"
#define STR_ROGER_END_TONE  "\x52\x4F\x47\x45\x52\x9C\x0B"
#define STR_VFO_SETTINGS  "\x1F\x1C\x1D\xBE\x07"
#define STR_ALL_SETTINGS  "\xD5\xD6\xBE\x07"
#define STR_DISABLE_ALL  "\x17\xD7\xD5\xD6"
#define STR_UNLOCK_ALL  "\xB8\xB9\xD5\xD6"
#define STR_FIVE_SECONDS  "\x35\x20\xC5"
#define STR_TEN_SECONDS  "\x31\x30\x20\xC5"
#define STR_TWENTY_SECONDS  "\x32\x30\x20\xC5"
#define STR_ON_TX  "\x0E\x0F\x8B"
#define STR_ON_RX  "\x05\x06\x8B"
#define STR_ON_TX_AND_RX  "\x0E\x0F\x2F\x05\x06\x8B"
#define STR_LIST  "\x83\x84"
#define STR_ALL  "\xD5\xD6"
#define STR_SCAN  "\x81\x82"
#define STR_LOW_VOLTAGE  "\xD8\x8D\x18"
#define STR_LONG_PRESS_HASH_TO_UNLOCK  "\xD9\xA1\x20\x23\x20\xA2\xB8\xB9"
#define STR_BUSY  "\x15\x16"
#define STR_TX_DISABLED  "\x17\xCE\x0E\xC8"
#define STR_TX_TIMEOUT  "\x0E\x0F\x8A\x8B"
#define STR_HIGH_VOLTAGE  "\xDA\x8D\x18"
#define STR_PRESS_EXIT_KEY  "\xA1\x20\x45\x58\x49\x54\x20\xA2"
#define STR_ALL_KEYS  "\xD5\xD6\xA1\xA2"
#define STR_UNLOCK  "\xB8\xB9"
#define STR_CTCSS  "\x0C\x0D\x09\x0B"
#define STR_DCS  "\x07\x08\x09\x0B"
#define STR_FREQUENCY  "\x03\x04"
#define STR_SAVE_PROMPT  "\x1A\x1B\x3F"
#define STR_SAVED  "\x1A\x1B\x3A"
#define STR_SCAN  "\x81\x82"
#define STR_DELETE_PROMPT  "\x1E\x1F\x3F"

#ifdef ENABLE_CUSTOM_SIDEFUNCTIONS

#define STR_SIDE_KEY1_SHORT_PRESS "\xA9\xA2\x31\xDB\xA1"
#define STR_SIDE_KEY1_LONG_PRESS "\xA9\xA2\x31\xD9\xA1"
#define STR_SIDE_KEY2_SHORT_PRESS "\xA9\xA2\x32\xDB\xA1"
#define STR_SIDE_KEY2_LONG_PRESS "\xA9\xA2\x32\xD9\xA1"
#define STR_M_KEY_LONG_PRESS "\x4D\xA2\xD9\xA1"
#define STR_FLASHLIGHT "\xDC\x8D"
#define STR_SWITCH_TX_POWER "\xDD\xDE\x0E\xC8\xDF\x04"
#define STR_MONITOR "\xE0\xE1"
#define STR_VOX_TX "\xE2\xE3\x0E\xC8"
#define STR_FM_RADIO "\x46\x4D\x06\x0B\xE4"
#define STR_LOCK_KEYPAD "\xB9\xE5\xA1\xA2"
#define STR_SWITCH_VFO "\xDD\xDE\x1C\x1D"
#define STR_SWITCH_VFO_MR_MODE "\xDD\xDE\x1C\x1D\x0C\x89"
#define STR_SWITCH_MODULATION "\xDD\xDE\xBB\xE6\x0C\x89"
#define STR_DTMF_DECODE "\x44\x54\x4D\x46\xB8\xA7"
#define STR_SWITCH_BANDWIDTH "\xDD\xDE\xE7\xE8\xE9"
#define STR_SQL_ADJUST "\xDD\xDE\xB3\xB4"
#define STR_BANDWIDTH "\xE7\xE8\xE9"
#define STR_WIDE_BAND "\xE7\xE9"
#define STR_NARROW_BAND "\xE8\xE9"
#ifdef ENABLE_SIDEFUNCTIONS_SEND
#define STR_MAIN_CH_TX "\xC7\x1C\x1D\x0E\xC8"
#define STR_SUB_CH_TX "\xCA\x1C\x1D\x0E\xC8"
#endif
#endif
#endif




#elif ENABLE_CHINESE_FULL==4
#define STR_STEP_FREQ "\xB2\xBD\xBD\xF8\xC6\xB5\xC2\xCA"
#define STR_RX_DCS "\xBD\xD3\xCA\xD5\xCA\xFD\xD7\xD6\xD1\xC7\xD2\xF4"
#define STR_RX_CTCSS "\xBD\xD3\xCA\xD5\xC4\xA3\xC4\xE2\xD1\xC7\xD2\xF4"
#define STR_TX_DCS "\xB7\xA2\xCB\xCD\xCA\xFD\xD7\xD6\xD1\xC7\xD2\xF4"
#define STR_TX_CTCSS "\xB7\xA2\xCB\xCD\xC4\xA3\xC4\xE2\xD1\xC7\xD2\xF4"
#define STR_TX_OFFSET_DIR "\xC6\xB5\xB2\xEE\xB7\xBD\xCF\xF2"
#define STR_TX_OFFSET_FREQ "\xC6\xB5\xB2\xEE\xC6\xB5\xC2\xCA"
#define STR_BUSY_CHANNEL_LOCKOUT "\xD3\xF6\xC3\xA6\xBD\xFB\xB7\xA2"
#define STR_COMPANDER "\xD1\xB9\xC0\xA9"
#define STR_SAVE_CHANNEL "\xB1\xA3\xB4\xE6\xD0\xC5\xB5\xC0"
#define STR_DELETE_CHANNEL "\xC9\xBE\xB3\xFD\xD0\xC5\xB5\xC0"
#define STR_NAME_CHANNEL "\xC3\xFC\xC3\xFB\xD0\xC5\xB5\xC0"
#define STR_CHANNEL_SCAN_LIST "\xD0\xC5\xB5\xC0\xC9\xA8\xC3\xE8\xC1\xD0\xB1\xED"
#define STR_SCAN_LIST1 "\xC9\xA8\xC3\xE8\xC1\xD0\xB1\xED\x31"
#define STR_SCAN_LIST2 "\xC9\xA8\xC3\xE8\xC1\xD0\xB1\xED\x32"
#define STR_SCAN_RESUME_MODE "\xCB\xD1\xCB\xF7\xBB\xD6\xB8\xB4\xC4\xA3\xCA\xBD"
#define STR_TX_TIMEOUT "\xB7\xA2\xCB\xCD\xB3\xAC\xCA\xB1"
#define STR_POWER_SAVE_MODE "\xCA\xA1\xB5\xE7\xC4\xA3\xCA\xBD"
#define STR_MIC_GAIN "\xC2\xF3\xBF\xCB\xB7\xE7\xD4\xF6\xD2\xE6"
#define STR_CHANNEL_DISPLAY_MODE "\xD0\xC5\xB5\xC0\xCF\xD4\xCA\xBE\xC4\xA3\xCA\xBD"
#define STR_AUTO_BACKLIGHT "\xD7\xD4\xB6\xAF\xB1\xB3\xB9\xE2"
#define STR_BACKLIGHT_BRIGHTNESS "\xB1\xB3\xB9\xE2\xC1\xC1\xB6\xC8"
#define STR_ROGER_BEEP "\xCA\xD7\xCE\xB2\xD2\xF4"
#define STR_TAIL_TONE_ELIM "\xCE\xB2\xD2\xF4\xCF\xFB\xB3\xFD"
#define STR_REPEATER_TAIL_TONE_ELIM "\xB9\xFD\xD6\xD0\xBC\xCC\xCE\xB2\xD2\xF4\xCF\xFB\xB3\xFD"
#define STR_ONE_KEY_CALL "\xB0\xB4\xBC\xFC\xBC\xB4\xBA\xF4"
#define DTMF_ID "\x44\x54\x4D\x46\x20\x49\x44"
#define STR_DTMF_UP_CODE "\x44\x54\x4D\x46\xC9\xCF\xCF\xDF\xC2\xEB"
#define STR_DTMF_DOWN_CODE "\x44\x54\x4D\x46\xCF\xC2\xCF\xDF\xC2\xEB"
#define STR_DTMF_PTT_ID "\x44\x54\x4D\x46\xB7\xA2\xCB\xCD"
#define STR_DTMF_SIDETONE "\x44\x54\x4D\x46\xB2\xE0\xD2\xF4"
#define STR_DTMF_RESPONSE "\x44\x54\x4D\x46\xCF\xEC\xD3\xA6"
#define STR_DTMF_HOLD "\x44\x54\x4D\x46\xB8\xB4\xCE\xBB"
#define STR_DTMF_PRELOAD "\x44\x54\x4D\x46\xD4\xA4\xD4\xD8\xB2\xA8"
#define STR_DTMF_CONTACTS "\x44\x54\x4D\x46\xC1\xAA\xCF\xB5\xC8\xCB"
#define STR_DTMF_LIVE_DISPLAY "\x44\x54\x4D\x46\xCF\xD4\xCA\xBE"
#define STR_AM_AUTO_GAIN "\x41\x4D\xD7\xD4\xB6\xAF\xD4\xF6\xD2\xE6"
#define STR_RX_TX_MODE "\xCA\xD5\xB7\xA2\xC4\xA3\xCA\xBD"
#define STR_SQUELCH_LEVEL "\xBE\xB2\xD4\xEB\xB5\xC8\xBC\xB6"
#define STR_BAND_UNLOCK "\xC6\xB5\xB6\xCE\xBD\xE2\xCB\xF8"
#define STR_TX_200M "\x32\x30\x30\x4D\xB7\xA2\xC9\xE4"
#define STR_TX_350M "\x33\x35\x30\x4D\xB7\xA2\xC9\xE4"
#define STR_TX_500M "\x35\x30\x30\x4D\xB7\xA2\xC9\xE4"
#define STR_RX_350M "\x33\x35\x30\x4D\xBD\xD3\xCA\xD5"
#define STR_BATTERY_CALIBRATION "\xB5\xE7\xB3\xD8\xB5\xF7\xD1\xB9"
#define STR_BATTERY_CAPACITY "\xB5\xE7\xB3\xD8\xB4\xF3\xD0\xA1"
#define STR_SETTINGS_RESET "\xB2\xCE\xCA\xFD\xB8\xB4\xCE\xBB"
#define STR_TX_EQ_RX "\xB7\xA2\xCB\xCD\x3D\xBD\xD3\xCA\xD5"
#define STR_TX_EQ_RX_PLUS_OFFSET "\xB7\xA2\xCB\xCD\x3D\n\xBD\xD3\xCA\xD5\x2B\xC6\xAB\xD2\xC6"
#define STR_TX_EQ_RX_MINUS_OFFSET "\xB7\xA2\xCB\xCD\x3D\n\xBD\xD3\xCA\xD5\x2D\xC6\xAB\xD2\xC6"
#define STR_OFF "\xB9\xD8\xB1\xD5"
#define STR_ON "\xBF\xAA\xC6\xF4"
#define STR_LEVEL_ONE "\x31\x20\xBC\xB6"
#define STR_LEVEL_TWO "\x32\x20\xBC\xB6"
#define STR_LEVEL_THREE "\x33\x20\xBC\xB6"
#define STR_LEVEL_FOUR "\x34\x20\xBC\xB6"
#define STR_THIRTY_SECONDS "\x33\x30\x20\xC3\xEB"
#define STR_ONE_MINUTE "\x31\x20\xB7\xD6"
#define STR_TWO_MINUTES "\x32\x20\xB7\xD6"
#define STR_THREE_MINUTES "\x33\x20\xB7\xD6"
#define STR_FOUR_MINUTES "\x34\x20\xB7\xD6"
#define STR_FIVE_MINUTES "\x35\x20\xB7\xD6"
#define STR_SIX_MINUTES "\x36\x20\xB7\xD6"
#define STR_SEVEN_MINUTES "\x37\x20\xB7\xD6"
#define STR_EIGHT_MINUTES "\x38\x20\xB7\xD6"
#define STR_NINE_MINUTES "\x39\x20\xB7\xD6"
#define STR_FIFTEEN_MINUTES "\x31\x35\x20\xB7\xD6"
#define STR_MAIN_CH_RX_TX "\xD6\xF7\xD0\xC5\xB5\xC0\n\xBD\xD3\xCA\xD5\xB7\xA2\xC9\xE4"
#define STR_DUAL_CH_RX "\xCB\xAB\xD0\xC5\xB5\xC0\n\xBD\xD3\xCA\xD5"
#define STR_MAIN_TX_SUB_RX "\xD6\xF7\xD0\xC5\xB5\xC0\xB7\xA2\xC9\xE4\n\xB8\xB1\xD0\xC5\xB5\xC0\xBD\xD3\xCA\xD5"
#define STR_MAIN_TX_DUAL_RX "\xD6\xF7\xD0\xC5\xB5\xC0\xB7\xA2\xC9\xE4\n\xCB\xAB\xD0\xC5\xB5\xC0\xBD\xD3\xCA\xD5"
#define STR_RESUME_5S_AFTER_SIGNAL "\xD3\xF6\xD0\xC5\xBA\xC5\n\x35\xC3\xEB\xBA\xF3\xCB\xD1\xCB\xF7"
#define STR_RESUME_WHEN_CARRIER_STOPS "\xD0\xC5\xBA\xC5\xCD\xA3\xD6\xB9\xBA\xF3\n\xCB\xD1\xCB\xF7"
#define STR_STOP_ON_SIGNAL "\xD3\xF6\xD0\xC5\xBA\xC5\xBA\xF3\n\xCD\xA3\xD6\xB9\xCB\xD1\xCB\xF7"
#define STR_FREQUENCY "\xC6\xB5\xC2\xCA"
#define STR_CHANNEL_NUMBER "\xD0\xC5\xB5\xC0\xBA\xC5"
#define STR_NAME "\xC3\xFB\xB3\xC6"
#define STR_NAME_PLUS_FREQ "\xC3\xFB\xB3\xC6\x2B\n\xC6\xB5\xC2\xCA"
#define STR_NO_RESPONSE "\xB2\xBB\xCF\xEC\xD3\xA6"
#define STR_LOCAL_RING "\xB1\xBE\xB5\xD8\xCF\xEC\xC1\xE5"
#define STR_REPLY_RESPONSE "\xBB\xD8\xB8\xB4\xCF\xEC\xD3\xA6"
#define STR_LOCAL_RING_AND_REPLY "\xB1\xBE\xB5\xD8\xCF\xEC\xC1\xE5\n\xBB\xD8\xB8\xB4\xCF\xEC\xD3\xA6"
#define STR_NO_SEND "\xB2\xBB\xB7\xA2\xCB\xCD"
#define STR_UP_CODE "\xC9\xCF\xCF\xDF\xC2\xEB"
#define STR_DOWN_CODE "\xCF\xC2\xCF\xDF\xC2\xEB"
#define STR_UP_PLUS_DOWN_CODE "\xC9\xCF\xCF\xDF\x2B\xCF\xC2\xCF\xDF\xC2\xEB"
#define STR_QUINDAR_CODE "\x51\x75\x69\x6E\x64\x61\x72\xC2\xEB"
#define STR_OFF "\xB9\xD8\xB1\xD5"
#define STR_ROGER_END_TONE "\x52\x4F\x47\x45\x52\xCE\xB2\xD2\xF4"
#define STR_VFO_SETTINGS "\xB3\xFD\xD0\xC5\xB5\xC0\xB2\xCE\xCA\xFD"
#define STR_ALL_SETTINGS "\xC8\xAB\xB2\xBF\xB2\xCE\xCA\xFD"
#define STR_DISABLE_ALL "\xBD\xFB\xD3\xC3\xC8\xAB\xB2\xBF"
#define STR_UNLOCK_ALL "\xBD\xE2\xCB\xF8\xC8\xAB\xB2\xBF"
#define STR_FIVE_SECONDS "\x35\x20\xC3\xEB"
#define STR_TEN_SECONDS "\x31\x30\x20\xC3\xEB"
#define STR_TWENTY_SECONDS "\x32\x30\x20\xC3\xEB"
#define STR_ON_TX "\xB7\xA2\xCB\xCD\xCA\xB1"
#define STR_ON_RX "\xBD\xD3\xCA\xD5\xCA\xB1"
#define STR_ON_TX_AND_RX "\xB7\xA2\xCB\xCD\x2F\xBD\xD3\xCA\xD5\xCA\xB1"
#define STR_ALL "\xC8\xAB\xB2\xBF"
#define STR_SCAN "\xC9\xA8\xC3\xE8"
#define STR_LOW_VOLTAGE "\xB5\xCD\xB5\xE7\xD1\xB9"
#define STR_LONG_PRESS_HASH_TO_UNLOCK "\xB3\xA4\xB0\xB4\x20\x23\x20\xBC\xFC\xBD\xE2\xCB\xF8"
#define STR_BUSY "\xD3\xF6\xC3\xA6"
#define STR_TX_DISABLED "\xBD\xFB\xD6\xB9\xB7\xA2\xC9\xE4"
#define STR_TX_TIMEOUT "\xB7\xA2\xCB\xCD\xB3\xAC\xCA\xB1"
#define STR_HIGH_VOLTAGE "\xB8\xDF\xB5\xE7\xD1\xB9"
#define STR_PRESS_EXIT_KEY "\xB0\xB4\x20\x45\x58\x49\x54\x20\xBC\xFC"
#define STR_ALL_KEYS "\xC8\xAB\xB2\xBF\xB0\xB4\xBC\xFC"
#define STR_UNLOCK "\xBD\xE2\xCB\xF8"
#define STR_SAVE_PROMPT "\xB1\xA3\xB4\xE6\x3F"
#define STR_SAVED "\xB1\xA3\xB4\xE6\x3A"
#define STR_SCAN "\xC9\xA8\xC3\xE8"
#define STR_DELETE_PROMPT "\xC9\xBE\xB3\xFD\x3F"
#define STR_LIST "\xC1\xD0\xB1\xED"
#define STR_CTCSS "\xC4\xA3\xC4\xE2\xD1\xC7\xD2\xF4"
#define STR_DCS "\xCA\xFD\xD7\xD6\xD1\xC7\xD2\xF4"
#define STR_PICTURE "\xCD\xBC\xC6\xAC"
#define STR_TEXT_MESSAGE "\xD0\xC5\xCF\xA2"
#define STR_SIDE_KEY1_SHORT_PRESS "\xB2\xE0\xBC\xFC\x31\xB6\xCC\xB0\xB4"
#define STR_SIDE_KEY1_LONG_PRESS "\xB2\xE0\xBC\xFC\x31\xB3\xA4\xB0\xB4"
#define STR_SIDE_KEY2_SHORT_PRESS "\xB2\xE0\xBC\xFC\x32\xB6\xCC\xB0\xB4"
#define STR_SIDE_KEY2_LONG_PRESS "\xB2\xE0\xBC\xFC\x32\xB3\xA4\xB0\xB4"
#define STR_M_KEY_LONG_PRESS "\x4D\xBC\xFC\xB3\xA4\xB0\xB4"
#define STR_FLASHLIGHT "\xCA\xD6\xB5\xE7\xCD\xB2"
#define STR_SWITCH_TX_POWER "\xC7\xD0\xBB\xBB\xB7\xA2\xC9\xE4\xB9\xA6\xC2\xCA"
#define STR_MONITOR "\xBC\xE0\xCC\xFD"
#define STR_VOX_TX "\xC9\xF9\xBF\xD8\xB7\xA2\xC9\xE4"
#define STR_FM_RADIO "\x46\x4D\xCA\xD5\xD2\xF4\xBB\xFA"
#define STR_LOCK_KEYPAD "\xCB\xF8\xB6\xA8\xB0\xB4\xBC\xFC"
#define STR_SWITCH_VFO "\xC7\xD0\xBB\xBB\xD0\xC5\xB5\xC0"
#define STR_SWITCH_VFO_MR_MODE "\xC7\xD0\xBB\xBB\xD0\xC5\xB5\xC0\xC4\xA3\xCA\xBD"
#define STR_SWITCH_MODULATION "\xC7\xD0\xBB\xBB\xB5\xF7\xD6\xC6\xC4\xA3\xCA\xBD"
#define STR_DTMF_DECODE "\x44\x54\x4D\x46\xBD\xE2\xC2\xEB"
#define STR_SWITCH_BANDWIDTH "\xC7\xD0\xBB\xBB\xBF\xED\xD5\xAD\xB4\xF8"
#define STR_SQL_ADJUST "\xC7\xD0\xBB\xBB\xBE\xB2\xD4\xEB"
#define STR_BANDWIDTH "\xBF\xED\xD5\xAD\xB4\xF8"
#define STR_WIDE_BAND "\xBF\xED\xB4\xF8"
#define STR_NARROW_BAND "\xD5\xAD\xB4\xF8"
#define STR_MAIN_CH_TX "\xD6\xF7\xD0\xC5\xB5\xC0\xB7\xA2\xC9\xE4"
#define STR_SUB_CH_TX "\xB8\xB1\xD0\xC5\xB5\xC0\xB7\xA2\xC9\xE4"
#define STR_POWER_ON_DISPLAY "\xBF\xAA\xBB\xFA\xCF\xD4\xCA\xBE"

#endif

#endif //UV_K5_FIRMWARE_CUSTOM_0_17_CHINESE_H
